apiVersion: v1
kind: Namespace
metadata:
  name: ryu

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryu-rest
  namespace: ryu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ryu-rest
  template:
    metadata:
      labels:
        app: ryu-rest
    spec:
      containers:
      - name: ryu-rest
        image: arturoalvarez/ryu-rest:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: rest
        - containerPort: 6633
          name: ofp
