apiVersion: v1
kind: Service
metadata:
  name: ryu-rest-lb
  namespace: ryu
spec:
  type: LoadBalancer
  selector:
    app: ryu-rest
  ports:
  - name: rest
    port: 8080
    targetPort: 8080
  - name: ofp
    port: 6633
    targetPort: 6633
